---
repos:
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        name: "Apply Black"
  - repo: https://github.com/nix-community/nixpkgs-fmt
    rev: f048515c9a98d7e2e4b034ec77641acc8a58098d
    hooks:
      - id: nixpkgs-fmt
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: debug-statements
        name: "Ensure debugger no debug statements exist"
      - id: trailing-whitespace
        name: "Remove trailing whitespaces"
