---
repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        name: "Apply Black"
        language_version: python3
        args: [
          "--target-version", "py311",
          "--exclude", '/(\.eggs|\.git|\.mypy_cache|\.tox|\.venv|_build|build|dist)/',
        ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: debug-statements
        name: "Ensure debugger no debug statements exist"
      - id: end-of-file-fixer
        name: "Ensure uniform file endings"
      - id: trailing-whitespace
        name: "Remove trailing whitespaces"
