language: python

cache:
  directories:
    - $HOME/.cache/pip

env:
  global:
    - CC_TEST_REPORTER_ID=2c769831e8bcd21982c6b17b4f9c166695dd0f7da4a2ad2ed551d28a040af81f

matrix:
  include:
    - name: "Tests - Python 3.8"
      python: 3.8
      env: TOX_ENV=py38
    - name: "Security - Python 3.8"
      python: 3.8
      env: TOX_ENV=security
    - name: "Style - Python 3.8"
      python: 3.8
      env: TOX_ENV=style
    - name: "Types - Python 3.8"
      python: 3.8
      env: TOX_ENV=types

before_install:
  - pip install poetry tox==3.15.1

install:
  - poetry install -v

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - tox -e $TOX_ENV

after_success:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TOX_ENV" == "py38" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
