sudo: false

language: python

cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - env: TOX_ENV=py36
      python: 3.6
    - env: TOX_ENV=flake8
      python: 3.6

before_install:
    - pip install -r requirements-dev.txt

install:
    - python setup.py install
    - pip install codecov==2.0.5

script: tox -e $TOX_ENV

after_success:
    - codecov
