[tool.poetry]
name = "volt"
version = "0.0.0"  # Placeholder version.
description = "Versatile static website generator"
authors = ["Wibowo Arindrarto <contact@arindrarto.dev>"]
readme = "README.md"
repository = "https://github.com/bow/volt"
license = "BSD-3-Clause"
keywords = ["static website"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.10",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Utilities",
]
packages = [
    { include = "volt" },
    { include = "tests", format = "sdist" },
]
include = [
    "CHANGELOG.rst",
    "README.rst",
    "LICENSE",
    "extras/volt",
]

[tool.poetry.scripts]
volt = "volt.cli:main"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"
pattern = "^v?(?P<base>\\d+\\.\\d+\\.\\d+)"

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.0.3"
jinja2 = "^3.0.3"
pygments = "^2.10.0"
pyyaml = "^6.0"
pendulum = "^2.1.2"
marshmallow = "^3.6.1"
markdown2 = "^2.4.1"
thefuzz = {extras = ["speedup"], version = "^0.19.0"}
python-slugify = "^5.0.2"
watchdog = "^2.1.6"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
bandit = "^1.6.2"
flake8 = "^3.8.4"
mypy = "^0.812"
mypy-extensions = "^0.4.3"
pytest-cov = "^2.11.1"
pytest-flake8 = "^1.0.7"
pytest-sugar = "^0.9.4"
radon = "^4.1.0"
flake8-polyfill = "^1.0.2"
black = "21.11b1"
safety = "^2.0.0"

[build-system]
requires = ["poetry>=1.1.4", "poetry-dynamic-versioning"]
build-backend = "poetry.masonry.api"
